CREATE DATABASE reviews;

CREATE TABLE product (
 id BIGSERIAL NOT NULL
);

ALTER TABLE product ADD CONSTRAINT product_pkey PRIMARY KEY (id);

CREATE TABLE reviews (
 id BIGSERIAL NOT NULL,
 rating INTEGER NOT NULL,
 summary VARCHAR(60) NOT NULL DEFAULT 'NULL',
 recommend INTEGER NOT NULL,
 response VARCHAR NOT NULL DEFAULT 'NULL',
 body VARCHAR(1000) NOT NULL DEFAULT 'NULL',
 date VARCHAR(30) NOT NULL DEFAULT 'NULL',
 helpfulness INTEGER(10) NOT NULL,
 id_product INTEGER
);

ALTER TABLE reviews ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

CREATE TABLE reviewers (
 id BIGSERIAL NOT NULL,
 nickname VARCHAR(60) NOT NULL DEFAULT 'NULL',
 email VARCHAR(60) NOT NULL DEFAULT 'NULL',
 id_reviews INTEGER NOT NULL
);

ALTER TABLE reviewers ADD CONSTRAINT reviewers_pkey PRIMARY KEY (id);

CREATE TABLE photos (
 id BIGSERIAL NOT NULL,
 url VARCHAR(200),
 id_reviews INTEGER NOT NULL
);

ALTER TABLE photos ADD CONSTRAINT photos_pkey PRIMARY KEY (id);

CREATE TABLE characteristics (
 id BIGSERIAL,
 name VARCHAR(60) NOT NULL DEFAULT 'NULL',
 char_id INTEGER NOT NULL,
 value VARCHAR(20) NOT NULL DEFAULT 'NULL',
 id_reviews INTEGER NOT NULL
);
